name: comic
channels:
  - conda-forge
dependencies:
  - cartopy
  - ipywidgets
  - python=3.10
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - pandas
  - plotly
  - scipy=1.9.1
  - seaborn
  - statsmodels
  - scikit-learn
  - xarray
  - xlrd
  - ipykernel
  - pip
  - pip:
      - reliability==0.8.6
